{% set name = "activity-browser" %}
{% set version = "2.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LCA-ActivityBrowser/{{ name }}/archive/{{ version }}.tar.gz
  sha256: edef8eae8433618c0c993343739b5525019c06e0c7687996a118943f65e18581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - activity-browser = activity_browser:run_activity_browser

requirements:
  host:
    - pip
    - python >=3.8,<=3.11,!=3.10
    - setuptools
  run:
    - python >=3.8,<=3.11,!=3.10
    - arrow
    - brightway2 =2.4.4
    - pyperclip
    - eidl >=2.0.1
    - libxml2 <=2.10.4
    - networkx
    - pint <=0.21
    - pyside2 >=5.15.5
    - qt-webengine
    - numpy >=1.23.5
    - salib >=1.4
    - seaborn

test:
  imports:
    - activity_browser
  # No test of activity-browser as no --help or --version available

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  summary: A graphical user interface for brightway2
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  dev_url: https://github.com/LCA-ActivityBrowser/activity-browser

extra:
  recipe-maintainers:
    - marc-vdm
    - bsteubing
    - haasad
    - m-rossi
    - mrvisscher
