{% set name = "activity-browser" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LCA-ActivityBrowser/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 855bb0fa983a325b8cf0608d6071cc62e5032f94bb257edcd53ecb0da2e6a2d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - activity-browser = activity_browser:run_activity_browser

requirements:
  host:
    - pip
    - python >=3.8,<3.10
    - setuptools
  run:
    - python >=3.8,<3.10
    - arrow
    - brightway2 >=2.4.2
    - pyperclip
    - eidl >=1.4.2
    - networkx
    - pyside2 >=5.15.5
    - qt-webengine
    - numpy =1.23.5
    - salib >=1.4
    - seaborn

test:
  imports:
    - activity_browser
  # No test of activity-browser as no --help or --version available

about:
  home: https://github.com/LCA-ActivityBrowser/activity-browser
  summary: A graphical user interface for brightway2
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  dev_url: https://github.com/LCA-ActivityBrowser/activity-browser

extra:
  recipe-maintainers:
    - marc-vdm
    - bsteubing
    - Zoophobus
    - haasad
    - m-rossi
